/**
 * useIlink — WeChat iLink notification channel (channel B) frontend lifecycle.
 *
 * Talks to the FIXED backend contract (behind cli-auth):
 *   GET  /ilink/status → IlinkStatus
 *   POST /ilink/login  → start scan-code login (QR appears via /ilink/qr)
 *   GET  /ilink/qr     → { dataUrl } (PNG data URL) | 204 when none pending
 *   POST /ilink/logout → tear down + clear state
 *
 * The channel is independent of Web Push: a user may connect WeChat only, Web
 * Push only, or both. After scanning, the user must send ONE message to the bot
 * to hand the server a context_token (the protocol only grants it with an inbound
 * message), after which agent-waiting events are pushed straight to WeChat.
 */
import { ref, type Ref } from 'vue'
import { useCliAuth } from '@terminal/composables/cli/useCliAuth'
import { cliApi } from '@terminal/composables/cli/useCliApiPrefix'

export interface IlinkStatus {
  loggedIn: boolean
  active: boolean
  dormant?: string
  sentCount: number
  maxSends: number
  userId?: string
  qrPending: boolean
}

export interface NotifyMetrics {
  events: number
  viaIlink: number
  viaWebPush: number
  fellBack: number
  undelivered: number
  lastAtMs: number
  lastChannel: string
}

export interface PushSubDetail {
  origin: string
  endpointTail: string
}

export interface WebPushStatus {
  subscriptions: number
  notifierRunning: boolean
  subs?: PushSubDetail[]
}

export interface NotifyTestResult {
  webPush: { sent: number; rejected: number; subs: number }
  ilink: { result: 'sent' | 'dormant' | 'ambiguous' | 'not-configured' }
}

export interface IlinkApi {
  status: Ref<IlinkStatus>
  metrics: Ref<NotifyMetrics>
  webPush: Ref<WebPushStatus>
  qrDataUrl: Ref<string>
  busy: Ref<boolean>     // login / logout
  testBusy: Ref<boolean> // dual-channel test (separate so button labels don't cross-talk)
  error: Ref<string>
  refresh(): Promise<void>
  startLogin(): Promise<void>
  logout(): Promise<void>
  testBoth(): Promise<{ cooldown?: boolean; result?: NotifyTestResult }>
  startPolling(): void
  stopPolling(): void
}

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms))

export function useIlink(): IlinkApi {
  const { cliFetch } = useCliAuth()
  const status = ref<IlinkStatus>({ loggedIn: false, active: false, sentCount: 0, maxSends: 10, qrPending: false })
  const metrics = ref<NotifyMetrics>({ events: 0, viaIlink: 0, viaWebPush: 0, fellBack: 0, undelivered: 0, lastAtMs: 0, lastChannel: '' })
  const webPush = ref<WebPushStatus>({ subscriptions: 0, notifierRunning: false })
  const qrDataUrl = ref('')
  const busy = ref(false)
  const testBusy = ref(false)
  const error = ref('')
  let pollTimer: ReturnType<typeof setInterval> | null = null

  // Single unified poll: /notify/status returns both channels + delivery metrics,
  // so the overview renders from one authoritative response (no per-channel races).
  async function refresh(): Promise<void> {
    try {
      const r = await cliFetch(cliApi('/notify/status'))
      if (r.ok) {
        const d = await r.json() as { ilink: IlinkStatus; metrics: NotifyMetrics; webPush: WebPushStatus }
        status.value = d.ilink
        metrics.value = d.metrics
        webPush.value = d.webPush
        // Once logged in (or no scan pending) the QR is stale — drop it.
        if (status.value.loggedIn || !status.value.qrPending) qrDataUrl.value = ''
      }
    } catch { /* transient — keep last known state */ }
  }

  async function fetchQR(): Promise<void> {
    try {
      const r = await cliFetch(cliApi('/ilink/qr'))
      if (r.status === 204) { qrDataUrl.value = ''; return }
      if (r.ok) {
        const q = await r.json() as { dataUrl?: string }
        qrDataUrl.value = q.dataUrl ?? ''
      }
    } catch { /* ignore */ }
  }

  async function startLogin(): Promise<void> {
    busy.value = true
    error.value = ''
    qrDataUrl.value = ''
    try {
      const r = await cliFetch(cliApi('/ilink/login'), { method: 'POST' })
      if (!r.ok) { error.value = '启动微信登录失败，请稍后重试。'; return }
      // Poll briefly for the QR to be generated by the SDK.
      for (let i = 0; i < 24 && !qrDataUrl.value; i++) {
        await fetchQR()
        if (qrDataUrl.value) break
        await sleep(500)
      }
      if (!qrDataUrl.value) error.value = '二维码生成超时，请重试。'
    } finally {
      busy.value = false
    }
  }

  async function testBoth(): Promise<{ cooldown?: boolean; result?: NotifyTestResult }> {
    testBusy.value = true
    try {
      const r = await cliFetch(cliApi('/notify/test'), { method: 'POST' })
      if (r.status === 429) return { cooldown: true }
      if (!r.ok) return {}
      const result = await r.json() as NotifyTestResult
      void refresh() // metrics advanced
      return { result }
    } catch {
      return {}
    } finally {
      testBusy.value = false
    }
  }

  async function logout(): Promise<void> {
    busy.value = true
    try {
      await cliFetch(cliApi('/ilink/logout'), { method: 'POST' })
      qrDataUrl.value = ''
      await refresh()
    } catch { /* ignore */ } finally {
      busy.value = false
    }
  }

  function startPolling(): void {
    stopPolling()
    void refresh()
    pollTimer = setInterval(() => {
      void refresh()
      if (!status.value.loggedIn && status.value.qrPending) void fetchQR()
    }, 2500)
  }

  function stopPolling(): void {
    if (pollTimer) { clearInterval(pollTimer); pollTimer = null }
  }

  return { status, metrics, webPush, qrDataUrl, busy, testBusy, error, refresh, startLogin, logout, testBoth, startPolling, stopPolling }
}
